In [7]:
import pandas as pd

print("Data Engineering Project")

Data Engineering Project

In [8]:
data = {
    "EmpID":[101,102,103],
    "Name":["Prasad","Rahul","Amit"],
    "Salary":[50000,60000,70000]
}

df = pd.DataFrame(data)

df

   EmpID    Name  Salary
0    101  Prasad   50000
1    102   Rahul   60000
2    103    Amit   70000

In [9]:
df["Bonus"] = df["Salary"] * 0.10

df

   EmpID    Name  Salary   Bonus
0    101  Prasad   50000  5000.0
1    102   Rahul   60000  6000.0
2    103    Amit   70000  7000.0

In [10]:
df.to_csv("data/employees.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'data'